"""
系统常量定义
"""
# StdLib
from decimal import Decimal

# 🎯 虚拟交易手续费配置（模拟实际交易所费率）- 使用Decimal确保精度
VIRTUAL_OPEN_FEE_RATE = Decimal('0.0002')   # 开仓手续费：0.02% (Maker)
VIRTUAL_CLOSE_FEE_RATE = Decimal('0.0005')  # 平仓手续费：0.05% (Taker)

# 💰 模拟交易初始资金与缓存键
VIRTUAL_ACCOUNT_INITIAL_BALANCE = 20.0  # 虚拟账户初始余额（USDT）
VIRTUAL_BALANCE_KEY = "virtual_account:balance"

# 🧪 回测默认参数
BACKTEST_DEFAULT_SYMBOL = "BTC/USDT"
BACKTEST_DEFAULT_DAYS = 60
BACKTEST_INITIAL_BALANCE = 20.0
BACKTEST_DEFAULT_LEVERAGE = 20.0
BACKTEST_DEFAULT_PRIMARY_TIMEFRAME = "5m"
BACKTEST_DEFAULT_TIMEFRAMES = ["3m", "5m", "15m"]

# =========================
# 交易信号与交易执行
# =========================
SIGNAL_MIN_INTERVAL_SECONDS = 180
SIGNAL_WARMUP_COUNT = 5
SIGNAL_BUFFER_DAYS = 30
SIGNAL_PREDICTION_CACHE_TTL = {"3m": 300, "5m": 600, "15m": 1200}
SIGNAL_FEATURE_CACHE_TTL = 300
SIGNAL_TIMEFRAME_WEIGHTS = {"3m": 0.15, "5m": 0.70, "15m": 0.15}
SIGNAL_PREDICTION_DAYS = {"3m": 10, "5m": 10, "15m": 10}
SIGNAL_MIN_REQUIRED_KLINES = 250

STOP_LOSS_PCT = 0.012
TAKE_PROFIT_PCT = 0.036
STOP_LOSS_PCT_FALLBACK = 0.015
TAKE_PROFIT_PCT_FALLBACK = 0.045

ADX_TRENDING_THRESHOLD = 30
ADX_RANGING_THRESHOLD = 25

POSITION_MAX_VALUE_USDT = 500000
POSITION_MIN_VALUE_USDT = 20
POSITION_MAX_SIZE = 1000
POSITION_MAX_DAILY_TRADES = 50

# =========================
# 风险与频率控制
# =========================
DRAWDOWN_WARNING_RATIO = 0.33
DRAWDOWN_CRITICAL_RATIO = 0.67
DRAWDOWN_CHECK_INTERVAL_SECONDS = 60
DRAWDOWN_LOOKBACK_DAYS = 30
DRAWDOWN_EVENT_THRESHOLD = 0.01
DRAWDOWN_CACHE_TTL_SECONDS = 300
DRAWDOWN_ALERT_CACHE_TTL_SECONDS = 3600

FREQUENCY_BASE_LIMIT = 0.3
FREQUENCY_MAX_DAILY_TRADES = 20
FREQUENCY_MIN_TRADE_INTERVAL_MINUTES = 15
FREQUENCY_FEE_RATE = 0.0007
FREQUENCY_TARGET_FEE_IMPACT = 0.05
FREQUENCY_VOLATILITY_THRESHOLD = 0.02
FREQUENCY_TREND_STRENGTH_THRESHOLD = 0.6
FREQUENCY_MIN_CONFIDENCE = 0.4
FREQUENCY_ATR_WINDOW = 14
FREQUENCY_TREND_FACTOR_BASE = 0.5
FREQUENCY_PERFORMANCE_FACTOR_BASE = 0.5
FREQUENCY_MIN_LIMIT = 0.05
FREQUENCY_MAX_LIMIT = 0.8
FREQUENCY_OVERFLOW_MULTIPLIER = 1.2
FREQUENCY_FEE_OVERFLOW_MULTIPLIER = 1.5

DIRECTION_CONSISTENCY_THRESHOLD = 0.7
DIRECTION_CONFIDENCE_THRESHOLD = 0.6
DIRECTION_STRENGTH_THRESHOLD = 0.5

RISK_FREE_RATE = 0.02
KELLY_MAX_POSITION_RATIO = 0.25
RISK_ATR_KLINES_COUNT = 100
RISK_METRICS_QUERY_LIMIT = 1000
RISK_ATR_WINDOW = 14
RISK_ATR_TAKE_PROFIT_MULTIPLIER = 3.6
RISK_ATR_TRAILING_STOP_MULTIPLIER = 1.0
RISK_FIXED_TRAILING_STOP_PCT = 0.01
RISK_VAR_LIMIT_PCT = 0.05
RISK_MONTE_CARLO_SIMULATIONS = 10000

# =========================
# 风险管理固定阈值（非环境变量）
# =========================
VAR_CONFIDENCE = 0.95  # VaR/ES默认置信度
MAX_DRAWDOWN_LIMIT = 0.15  # 最大回撤比例（15%）
KELLY_MULTIPLIER = 0.25  # Kelly系数乘数

# =========================
# 机器学习与特征
# =========================
# 训练数据天数配置（统一使用270天，最大化数据利用）
TRAINING_BASE_DAYS_CONFIG = {"3m": 180, "5m": 180, "15m": 180}  # 基础天数
TRAINING_DAYS_MULTIPLIER = 1.5  # Ensemble模型统一倍数（180 × 1.5 = 270天）

LABEL_WINDOW_CONFIG = {"3m": 20, "5m": 24, "15m": 32}
LABEL_PT_SL_CONFIG = {"3m": (2.2, 1.6), "5m": (2.2, 1.8), "15m": (2.5, 2.0)}
LABEL_VOLATILITY_WINDOW = 20
LABEL_VOLATILITY_DEFAULT = 0.002
LABEL_VOLATILITY_MIN = 0.001

LGB_N_ESTIMATORS = 300
LGB_NUM_LEAVES = 31
LGB_LEARNING_RATE = 0.05
LGB_FEATURE_FRACTION = 0.8
LGB_BAGGING_FRACTION = 0.8
LGB_BAGGING_FREQ = 5
LGB_MAX_DEPTH = 6
LGB_MIN_CHILD_SAMPLES = 40
LGB_REG_ALPHA = 0.5
LGB_REG_LAMBDA = 0.5
LGB_MIN_SPLIT_GAIN = 0.02

FEATURE_IMPORTANCE_THRESHOLD_HIGH = 0.1
FEATURE_IMPORTANCE_THRESHOLD_LOW = 0.01

EFFECTIVE_SAMPLE_BETA_BASE = 0.999
EFFECTIVE_SAMPLE_BETA_NON_3M = 0.995

OPTUNA_N_TRIALS = 100
OPTUNA_TIMEOUT_SECONDS = 1800
INFORMER_N_TRIALS = 20
INFORMER_TIMEOUT_SECONDS = 3600

INFORMER_D_MODEL = 128
INFORMER_N_HEADS = 8
INFORMER_N_LAYERS = 3
INFORMER_EPOCHS = 50
INFORMER_BATCH_SIZE = 256
INFORMER_LEARNING_RATE = 0.0005
INFORMER_SEQ_LEN_CONFIG = {"3m": 96, "5m": 96, "15m": 64}
INFORMER_WARMUP_EPOCHS = 5
INFORMER_MAX_NAN_INF_TOLERANCE = 30
INFORMER_MAX_CONSECUTIVE_NAN_INF = 8
INFORMER_GRAD_CLIP_NORM = 2.0

ENSEMBLE_FALLBACK_WEIGHTS = {"lgb": 0.4, "xgb": 0.3, "cat": 0.3}

STABILITY_N_BAGGING_MODELS = 5
STABILITY_BOOTSTRAP_RATIO = 0.8
STABILITY_FEATURE_SAMPLING_RATIO = 0.8
STABILITY_DIVERSITY_THRESHOLD = 0.3
STABILITY_STABILITY_THRESHOLD = 0.8

# =========================
# 机器学习损失函数配置
# =========================
USE_GMADL_LOSS = False  # 生产默认使用稳定的交叉熵损失
GMADL_ALPHA = 1.0  # GMADL损失alpha
GMADL_BETA = 0.5  # GMADL损失beta

GMADL_PROB_MIN = 1e-7
GMADL_PROB_MAX = 1.0 - 1e-7
GMADL_ERROR_MIN = 1e-7

# 致命错误惩罚配置（用于降低LONG↔SHORT错误率）
USE_FATAL_ERROR_PENALTY = True  # 是否启用致命错误惩罚
FATAL_ERROR_WEIGHT = 5.0  # 致命错误权重（LONG↔SHORT错误的惩罚倍数）
HOLD_WEIGHT_MULTIPLIER = 15.0  # HOLD类别权重倍数（提升HOLD识别能力）

MOMENTUM_ROC_PERIODS = [5, 10, 20]
MOMENTUM_MOMENTUM_PERIODS = [5, 10, 20]
MOMENTUM_RSI_WINDOW = 14
MOMENTUM_RSI_ACCEL_SHIFT = 1
FEATURE_EPS = 1e-10
FEATURE_STD_EPS = 1e-8

PRICE_CHANGE_PERIODS = [2, 3, 5, 10, 20]
PRICE_ACCELERATION_SHIFTS = [1, 3, 5]
PRICE_MOMENTUM_WINDOW = 5

VOLUME_SMA_WINDOW = 20
VOLUME_OBV_SMA_WINDOW = 20
VWAP_WINDOW = 20
VOLUME_BREAKOUT_FAST_WINDOW = 5
VOLUME_BREAKOUT_SLOW_WINDOW = 20
PRICE_CHANGE_SHORT_WINDOW = 1
PRICE_CHANGE_LONG_WINDOW = 5
VOLUME_CHANGE_WINDOW = 5
VOLUME_WEIGHTED_WINDOW = 20

ORDER_FLOW_EPS = 1e-10
ORDER_FLOW_LARGE_WINDOW = 20
ORDER_FLOW_LARGE_STD_MULTIPLIER = 2
ORDER_FLOW_CUM_WINDOWS = [5, 10, 20]

MICROSTRUCTURE_POSITION_WINDOWS = [5, 20, 50]
MICROSTRUCTURE_OVERBOUGHT_THRESHOLD = 0.8
MICROSTRUCTURE_OVERSOLD_THRESHOLD = 0.2
MICROSTRUCTURE_PRICE_RANGE_EPS = 1e-10
MICROSTRUCTURE_BODY_STRONG_RATIO = 0.6
MICROSTRUCTURE_DOJI_RATIO = 0.1
MICROSTRUCTURE_EFFICIENCY_PERIODS = [5, 10, 20]
MICROSTRUCTURE_FRACTAL_PERIODS = [10, 20]
MICROSTRUCTURE_HURST_PERIODS = [20, 50]
MICROSTRUCTURE_ATR_EPS = 1e-10

MTF_INTERVAL_3M_MAX = 3.5
MTF_INTERVAL_5M_MAX = 7.5
MTF_INTERVAL_15M_MAX = 22.5
MTF_RESAMPLE_MAP = {"3m": "3min", "5m": "5min", "15m": "15min"}
MTF_SMA_FAST_WINDOW = 20
MTF_SMA_SLOW_WINDOW = 50
MTF_RSI_WINDOW = 14
MTF_VOLATILITY_WINDOW = 20
MTF_SHIFT_LAG = 1

PATTERN_SHADOW_MULTIPLIER = 2
PATTERN_SHADOW_SMALL_RATIO = 0.5
PATTERN_DOJI_RATIO = 0.1
PATTERN_GAP_EPS = 1e-10
PATTERN_SHIFT_1 = 1
PATTERN_SHIFT_2 = 2

SENTIMENT_SHORT_VOL_WINDOW = 20
SENTIMENT_LONG_VOL_WINDOW = 100
SENTIMENT_EPS = 1e-10
SENTIMENT_RSI_OVERBOUGHT = 70
SENTIMENT_RSI_OVERSOLD = 30
SENTIMENT_RSI_MOMENTUM_SHIFT = 5
SENTIMENT_RSI_VOL_WINDOW = 10
SENTIMENT_VOLUME_MA_WINDOW = 20
SENTIMENT_VOLUME_SURGE_MULTIPLIER = 2
SENTIMENT_VOLUME_DRY_MULTIPLIER = 0.5
SENTIMENT_PRICE_TREND_WINDOW = 5
SENTIMENT_VOLUME_TREND_WINDOW = 5
SENTIMENT_VOL_REGIME_SHORT = 20
SENTIMENT_VOL_REGIME_LONG = 100
SENTIMENT_SMA_TREND_SHIFT = 1
SENTIMENT_MACD_NORM_PCT = 0.01
SENTIMENT_SCORE_WINDOW = 10
SENTIMENT_PRESSURE_MA_WINDOW = 5
SENTIMENT_VOLUME_WEIGHTED_WINDOW = 10
SENTIMENT_VOLUME_STD_WINDOW = 20
SENTIMENT_MARKET_BREADTH_WINDOWS = [5, 20, 50]
SENTIMENT_EXTREME_WINDOW = 50
SENTIMENT_EXTREME_STD_MULTIPLIER = 2
SENTIMENT_EXTREME_DECAY_WINDOW = 5

SWING_WINDOWS = [5, 10]
SWING_RANGE_WINDOWS = [20, 50]
SWING_RANGE_EPS = 1e-10
SWING_FREQUENCY_WINDOW = 50
SWING_CENTER_MULTIPLIER = 2

TREND_ADX_WEAK = 20
TREND_ADX_STRONG = 40
TREND_SLOPE_WINDOWS = [5, 10, 20]
TREND_SMA_WINDOWS = [5, 10, 20]
TREND_EMA_FAST = 12
TREND_EMA_SLOW = 26
TREND_EPS = 1e-10
SUPPORT_RESISTANCE_WINDOWS = [10, 20, 50]
BREAKOUT_WINDOWS = [20, 50]
TREND_BREAKOUT_SHIFT = 1

# =========================
# 数据服务与接口
# =========================
WS_RECONNECT_DELAY_SECONDS = 5
WS_DEFAULT_INTERVAL_MS = 60 * 1000
HISTORICAL_DATA_BATCH_SIZE = 1000
HISTORICAL_DATA_RATE_LIMIT_DELAY = 0.1
HEALTH_CHECK_INTERVAL_SECONDS = 300
HEALTH_DATA_FRESHNESS_SECONDS = 60
HEALTH_BUFFER_MIN_SIZE = 200
HEALTH_CHECK_QUERY_LIMIT = 100
ALERT_CACHE_TTL_SECONDS = 3600
DEBUG_LOG_PROBABILITY = 0.01

# =========================
# WebSocket重连与心跳
# =========================
WS_RECONNECT_INITIAL_DELAY = 1.0  # 初始重连延迟（秒）
WS_RECONNECT_MAX_DELAY = 60.0  # 最大重连延迟（秒）
WS_RECONNECT_BACKOFF_FACTOR = 2.0  # 退避因子
WS_RECONNECT_MAX_RETRIES = 10  # 最大重试次数
WS_PING_INTERVAL = 30  # 心跳ping间隔（秒）
WS_PONG_TIMEOUT = 10  # pong超时时间（秒）
WS_SSL_TIMEOUT = 30  # SSL握手超时（秒）

# =========================
# GradScaler配置（自动混合精度）
# =========================
# 🔧 优化：降低增长因子和增长间隔，减少Scale值过大问题
GRAD_SCALER_GROWTH_FACTOR = 1.1  # 从1.2降低到1.1，更保守的增长策略
GRAD_SCALER_GROWTH_INTERVAL = 3000  # 从2000增加到3000，增长更慢
GRAD_SCALER_MAX_SCALE = 50000.0  # 从100000.0降低到50000.0，更早触发重置
GRAD_SCALER_AUTO_RESET = True  # 是否启用自动重置
GRAD_SCALER_RESET_THRESHOLD_EPOCHS = 3  # 触发重置的epoch阈值
GRAD_SCALER_MAX_CONSECUTIVE_OVERFLOW = 5  # 最大连续溢出次数

# =========================
# 交易所客户端
# =========================
BINANCE_MAX_INITIAL_RETRIES = 3
BINANCE_PERIODIC_RETRY_INTERVAL_SECONDS = 120.0
BINANCE_RECV_WINDOW_MS = 60000
BINANCE_MAX_WAIT_SECONDS = 10
BINANCE_MESSAGE_TIMEOUT_SECONDS = 1200
BINANCE_WARNING_TIMEOUT_SECONDS = 600
BINANCE_API_MAX_LIMIT = 1500
BINANCE_API_LIMIT_LARGE = 1000
BINANCE_API_LIMIT_MEDIUM = 500
BINANCE_RATE_LIMIT_DELAY_SECONDS = 0.2

OKX_API_LIMIT_LARGE = 300
OKX_API_LIMIT_MEDIUM = 100
OKX_PING_TIMEOUT_SECONDS = 10
OKX_DEFAULT_INTERVAL_MS = 60 * 1000
OKX_MAX_RETRIES = 3

# =========================
# 数据库
# =========================
DB_POOL_RECYCLE_SECONDS = 3600

# =========================
# API默认参数
# =========================
API_SIGNAL_RECENT_HOURS = 1
API_SIGNAL_RECENT_LIMIT = 1
API_SIGNAL_HISTORY_LIMIT = 1000
API_SIGNAL_LATEST_DATA_LIMIT = 200
API_SIGNALS_HISTORY_HOURS = 24
API_SIGNALS_HISTORY_LIMIT = 100
API_SIGNALS_PERFORMANCE_DAYS = 7
API_SIGNALS_SUMMARY_DAYS = 30
SIGNAL_API_DELAY_SECONDS = 0.1
SIGNAL_HOLD_WEIGHT_DECAY = 0.5

# =========================
# 调度器
# =========================
SCHEDULER_MODEL_TRAINING_DAY = 5
SCHEDULER_DATA_UPDATE_INTERVAL_HOURS = 1
SCHEDULER_DATA_INTEGRITY_CHECK_INTERVAL_HOURS = 6

# =========================
# 交易安全参数
# =========================
TRADING_SAFE_STOP_LOSS_LONG_PCT = 0.985
TRADING_SAFE_TAKE_PROFIT_LONG_PCT = 1.03
TRADING_SAFE_STOP_LOSS_SHORT_PCT = 1.015
TRADING_SAFE_TAKE_PROFIT_SHORT_PCT = 0.97

# =========================
# 集成学习
# =========================
ENSEMBLE_TRAIN_SPLIT_RATIO = 0.6
ENSEMBLE_VAL_SPLIT_RATIO = 0.8
ENSEMBLE_META_HOLD_PENALTY_WEIGHTS = {0.60: 0.45, 0.50: 0.55, 0.40: 0.65, 0.0: 0.75}
ENSEMBLE_META_TIME_DECAY_FACTOR = 0.1
ENSEMBLE_MAX_SPLITS = 5
ENSEMBLE_META_LEARNER_PARAMS = {
    # Phase 2修复：优化元学习器配置（防过拟合，提升泛化能力）
    "n_estimators": 200,  # 增加（更强大）
    "max_depth": 5,  # 降低（防过拟合）
    "learning_rate": 0.03,  # 降低（更稳定）
    "num_leaves": 24,  # 降低（防过拟合，2^5-1=31 → 2^4.5≈24）
    "min_child_samples": 30,  # 增加（防过拟合）
    "subsample": 0.7,  # 降低（防过拟合）
    "colsample_bytree": 0.7,  # 降低（防过拟合）
    "reg_alpha": 0.3,  # 增加（更强正则化）
    "reg_lambda": 0.3,  # 增加（更强正则化）
    "feature_fraction": 0.8,  # 新增（特征采样，防过拟合）
    "bagging_freq": 5,  # 新增（Bagging频率）
    "random_state": 42,
    "verbose": -1
}

# =========================
# 优化器
# =========================
OPTIMIZER_LR_REDUCE_FACTOR = 0.5
OPTIMIZER_LR_REDUCE_THRESHOLD = 1e-4

